# Full documentation https://wiki.hyprland.org

monitor=,2560x1440,auto,1

exec-once = waybar
exec-once = hyprpaper
exec-once = dunst
exec-once = flatpak run org.telegram.desktop

env = XCURSOR_SIZE,24
# XDG Desktop Portal
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland

# QT
env = QT_QPA_PLATFORM,wayland;xcb
env = QT_QPA_PLATFORMTHEME,qt6ct
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = QT_AUTO_SCREEN_SCALE_FACTOR,1

# GTK
env = GDK_SCALE,1

# Mozilla
env = MOZ_ENABLE_WAYLAND,1

# Set the cursor size for xcursor
env = XCURSOR_SIZE,24

# Disable appimage launcher by default
env = APPIMAGELAUNCHER_DISABLE,1

# OZONE
env = OZONE_PLATFORM,wayland

# For KVM virtual machines
# env = WLR_NO_HARDWARE_CURSORS, 1
# env = WLR_RENDERER_ALLOW_SOFTWARE, 1

# NVIDIA https://wiki.hyprland.org/Nvidia/
# env = LIBVA_DRIVER_NAME,nvidia
# env = GBM_BACKEND,nvidia-drm
# env = __GLX_VENDOR_LIBRARY_NAME,nvidia
# env = __GL_VRR_ALLOWED,1
# env = WLR_DRM_NO_ATOMIC,1

input {
    kb_layout = us,ru
    kb_variant =
    kb_model =
    kb_options = grp:alt_shift_toggle
    kb_rules =

    follow_mouse = 1

    touchpad {
        natural_scroll = false
    }

    sensitivity = -0.5 # -1.0 - 1.0, 0 means no modification.

}

general {
    gaps_in = 1
    gaps_out = 1
    border_size = 4
    col.active_border = rgba(e5c07bee) rgba(98c379ee) 45deg
    col.inactive_border = rgba(abb2bfbb)
    layout = dwindle
    resize_on_border = true
}

decoration {
    rounding = 0
    blur {
        enabled = true
        size = 1
        passes = 1
    }
    inactive_opacity = 0.9
    active_opacity = 1.0
    shadow {
        enabled = false
        range = 10
        color = rgba(2e2e2eee)
    }
}

animations {
    enabled = false
    bezier = myBezier, 0.05, 0.9, 0.1, 1.05
    animation = windows, 1, 7, myBezier
    animation = windowsOut, 1, 7, default, popin 80%
    animation = border, 1, 10, default
    animation = borderangle, 1, 8, default
    animation = fade, 1, 7, default
    animation = workspaces, 1, 6, default
}

dwindle {
    # See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
    pseudotile = true # master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = true # you probably want this
}

master {
    # See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
}

# See https://wiki.hyprland.org/Configuring/Variables/ for more
gestures {
    # workspace_swipe = true
}
# See https://wiki.hyprland.org/Configuring/Variables/ for more
misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
}

# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

# binds:
source = ~/.config/hypr/binds.conf
