#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.
#   1. put it into /etc/grub.d/40_custom
#   2. run `sudo grub-mkconfig -o /boot/grub/grub.cfg`
menuenty "Win 10" --class windows {
	insmod part_msdos
	set root=(hd2,msdos1)
	chainloader +1
}
